# Here, we include the dotnet core SDK as the base to build our app
FROM mcr.microsoft.com/dotnet/core/sdk:5.0 AS Build-Client
# Setting the work directory for our app
WORKDIR /app/Client

# We copy the .csproj of our app to root and 
# restore the dependencies of the project.
COPY BlazorApp.Client.csproj .
RUN dotnet restore "BlazorApp.Client.csproj"

# We proceed by copying all the contents in
# the main project folder to root and build it
COPY . .
RUN dotnet build "BlazorApp.Client.csproj" -c Release -o /build

# Once we're done building, we'll publish the project
# to the publish folder 
FROM Build-Client AS publish
RUN dotnet publish "BlazorApp.Client.csproj" -c Release -o /publish

# We then get the base image for Nginx and set the 
# work directory 
FROM nginx:alpine AS final
WORKDIR /usr/share/nginx/html

# We'll copy all the contents from wwwroot in the publish
# folder into nginx/html for nginx to serve. The destination
# should be the same as what you set in the nginx.conf.
COPY --from=publish /publish/wwwroot /usr/local/webapp/nginx/html
COPY Nginx/nginx.conf /etc/nginx/nginx.conf